from pathlib import Path
import os
import sqlite3

import psycopg
from dotenv import load_dotenv
from psycopg import sql


BASE_DIR = Path(__file__).resolve().parents[1]
SQLITE_PATH = BASE_DIR / "data" / "jobs.db"
ENV_PATH = BASE_DIR / ".env"

load_dotenv(ENV_PATH)

DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is missing from backend/.env")


TABLE_ORDER = [
    "companies",
    "employers",
    "collection_runs",
    "sponsor_rollup",
    "jobs",
    "sponsor_history",
    "employer_sources",
    "job_skills",
]


POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    website TEXT,
    careers_url TEXT,
    created_at TEXT,
    updated_at TEXT
);

CREATE TABLE IF NOT EXISTS employers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    source_type TEXT NOT NULL DEFAULT 'DIRECT_EMPLOYER',
    website TEXT,
    careers_url TEXT,
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TEXT,
    updated_at TEXT
);

CREATE TABLE IF NOT EXISTS collection_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TEXT,
    completed_at TEXT,
    hours_lookback INTEGER NOT NULL,
    jobs_found INTEGER DEFAULT 0,
    jobs_added INTEGER DEFAULT 0,
    jobs_updated INTEGER DEFAULT 0,
    status TEXT DEFAULT 'RUNNING',
    error_message TEXT
);

CREATE TABLE IF NOT EXISTS sponsor_rollup (
    normalized_name TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'DOL_OFLC_LCA',
    total_filings INTEGER NOT NULL DEFAULT 0,
    approved_count INTEGER NOT NULL DEFAULT 0,
    denied_count INTEGER NOT NULL DEFAULT 0,
    recent_filings INTEGER NOT NULL DEFAULT 0,
    latest_year INTEGER,
    sponsor_strength TEXT NOT NULL DEFAULT 'UNKNOWN',
    last_verified_at TEXT
);

CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    external_id TEXT,
    source TEXT NOT NULL,
    source_url TEXT NOT NULL UNIQUE,
    apply_url TEXT,

    company_id BIGINT,

    company_name_raw TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    location_raw TEXT,
    country TEXT,

    posted_at TEXT,
    first_seen_at TEXT,
    last_seen_at TEXT,

    min_experience_years DOUBLE PRECISION,
    max_experience_years DOUBLE PRECISION,
    experience_text TEXT,
    experience_match INTEGER,

    work_arrangement TEXT,
    employment_type TEXT,

    visa_language_status TEXT,
    visa_evidence_text TEXT,

    h1b_history_strength TEXT,

    sponsorship_score DOUBLE PRECISION DEFAULT 0,
    overall_score DOUBLE PRECISION DEFAULT 0,

    decision TEXT,
    decision_reason TEXT,

    application_status TEXT DEFAULT 'NEW',
    date_applied TEXT,
    notes TEXT,

    source_type TEXT DEFAULT 'DIRECT_EMPLOYER',
    ats TEXT,
    experience_band TEXT,

    visa_detail_status TEXT,

    agency_name TEXT,
    end_client TEXT,

    employment_detail_type TEXT,

    CONSTRAINT jobs_company_fk
        FOREIGN KEY(company_id)
        REFERENCES companies(id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS sponsor_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT NOT NULL,

    source TEXT NOT NULL,
    source_year INTEGER,

    filings_count INTEGER,
    approved_count INTEGER,
    denied_count INTEGER,

    sponsor_strength TEXT DEFAULT 'UNKNOWN',

    evidence_url TEXT,
    last_verified_at TEXT,

    CONSTRAINT sponsor_history_company_fk
        FOREIGN KEY(company_id)
        REFERENCES companies(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS employer_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    employer_id BIGINT NOT NULL,

    ats TEXT NOT NULL,
    token TEXT,
    careers_url TEXT,

    enabled INTEGER NOT NULL DEFAULT 1,

    last_checked_at TEXT,
    last_success_at TEXT,

    active_jobs INTEGER DEFAULT 0,
    source_verified INTEGER DEFAULT 0,

    notes TEXT,

    CONSTRAINT employer_sources_employer_fk
        FOREIGN KEY(employer_id)
        REFERENCES employers(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS job_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    job_id BIGINT NOT NULL,

    skill TEXT NOT NULL,
    matched_to_profile INTEGER DEFAULT 0,

    CONSTRAINT job_skills_job_fk
        FOREIGN KEY(job_id)
        REFERENCES jobs(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_jobs_posted_at
ON jobs(posted_at);

CREATE INDEX IF NOT EXISTS idx_jobs_application_status
ON jobs(application_status);

CREATE INDEX IF NOT EXISTS idx_jobs_work_arrangement
ON jobs(work_arrangement);

CREATE INDEX IF NOT EXISTS idx_jobs_source_type
ON jobs(source_type);

CREATE INDEX IF NOT EXISTS idx_jobs_agency
ON jobs(agency_name);

CREATE INDEX IF NOT EXISTS idx_jobs_sponsor_strength
ON jobs(h1b_history_strength);

CREATE INDEX IF NOT EXISTS idx_jobs_overall_score
ON jobs(overall_score);

CREATE INDEX IF NOT EXISTS idx_sponsor_rollup_strength
ON sponsor_rollup(sponsor_strength);
"""


def get_sqlite_rows(conn, table):
    conn.row_factory = sqlite3.Row

    rows = conn.execute(
        f'SELECT * FROM "{table}"'
    ).fetchall()

    return [dict(row) for row in rows]


def postgres_table_count(conn, table):
    with conn.cursor() as cur:
        cur.execute(
            sql.SQL("SELECT COUNT(*) FROM {}").format(
                sql.Identifier(table)
            )
        )

        return cur.fetchone()[0]


def insert_rows(pg_conn, table, rows):
    if not rows:
        return 0

    columns = list(rows[0].keys())

    query = sql.SQL(
        "INSERT INTO {} ({}) VALUES ({})"
    ).format(
        sql.Identifier(table),

        sql.SQL(", ").join(
            sql.Identifier(column)
            for column in columns
        ),

        sql.SQL(", ").join(
            sql.Placeholder()
            for _ in columns
        ),
    )

    values = [
        tuple(row[column] for column in columns)
        for row in rows
    ]

    with pg_conn.cursor() as cur:
        cur.executemany(query, values)

    return len(values)


def reset_identity(pg_conn, table):
    with pg_conn.cursor() as cur:
        cur.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = %s
              AND column_name = 'id'
            """,
            (table,),
        )

        if not cur.fetchone():
            return

        cur.execute(
            """
            SELECT pg_get_serial_sequence(%s, 'id')
            """,
            (table,),
        )

        sequence = cur.fetchone()[0]

        if not sequence:
            return

        cur.execute(
            sql.SQL(
                """
                SELECT setval(
                    %s,
                    COALESCE(MAX(id), 1),
                    MAX(id) IS NOT NULL
                )
                FROM {}
                """
            ).format(sql.Identifier(table)),
            (sequence,),
        )


def main():
    print("SQLite source:")
    print(SQLITE_PATH)

    if not SQLITE_PATH.exists():
        raise FileNotFoundError(
            f"SQLite database not found: {SQLITE_PATH}"
        )

    sqlite_conn = sqlite3.connect(SQLITE_PATH)
    sqlite_conn.row_factory = sqlite3.Row

    print("\nConnecting to Supabase...")

    with psycopg.connect(
        DATABASE_URL,
        connect_timeout=20
    ) as pg_conn:

        print("CONNECTED")

        with pg_conn.cursor() as cur:
            cur.execute(POSTGRES_SCHEMA)

        pg_conn.commit()

        print("\nPostgres schema created.")

        print("\nChecking whether target tables are empty...")

        populated = []

        for table in TABLE_ORDER:
            count = postgres_table_count(
                pg_conn,
                table
            )

            print(
                f"{table}: {count} existing rows"
            )

            if count > 0:
                populated.append(
                    (table, count)
                )

        if populated:
            print("\nSTOPPING.")
            print(
                "Supabase already contains data."
            )
            print(
                "This migration will NOT overwrite it."
            )

            for table, count in populated:
                print(
                    f" - {table}: {count}"
                )

            return

        print("\nStarting migration...\n")

        results = {}

        for table in TABLE_ORDER:

            rows = get_sqlite_rows(
                sqlite_conn,
                table
            )

            print(
                f"{table}: copying "
                f"{len(rows)} rows..."
            )

            inserted = insert_rows(
                pg_conn,
                table,
                rows
            )

            results[table] = {
                "sqlite": len(rows),
                "postgres": inserted,
            }

            pg_conn.commit()

        print("\nResetting identity sequences...")

        for table in TABLE_ORDER:
            reset_identity(
                pg_conn,
                table
            )

        pg_conn.commit()

        print("\nVERIFYING ROW COUNTS")
        print("=" * 60)

        all_good = True

        for table in TABLE_ORDER:

            sqlite_count = sqlite_conn.execute(
                f'SELECT COUNT(*) FROM "{table}"'
            ).fetchone()[0]

            postgres_count = postgres_table_count(
                pg_conn,
                table
            )

            match = (
                sqlite_count ==
                postgres_count
            )

            if not match:
                all_good = False

            print(
                f"{table:20} "
                f"SQLite={sqlite_count:<8} "
                f"Postgres={postgres_count:<8} "
                f"{'OK' if match else 'MISMATCH'}"
            )

        print("=" * 60)

        if all_good:
            print(
                "\nMIGRATION COMPLETED SUCCESSFULLY"
            )
        else:
            print(
                "\nMIGRATION FINISHED WITH COUNT MISMATCHES"
            )

    sqlite_conn.close()


if __name__ == "__main__":
    main()
